version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: tsunaimi-frontend-production
    ports:
      - "3200:3000"
    env_file:
      - .env.production
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    depends_on:
      - postgresql
    networks:
      - tsunaimi-network-production

  postgresql:
    build:
      context: .
      dockerfile: docker/postgresql/Dockerfile
    container_name: tsunaimi-postgresql-production
    ports:
      - "5632:5432"
    env_file:
      - .env.production
    volumes:
      - tsunaimi-postgresql-data-production:/var/lib/postgresql/data
    networks:
      - tsunaimi-network-production

networks:
  tsunaimi-network-production:
    name: tsunaimi-network-production

volumes:
  tsunaimi-postgresql-data-production:
    name: tsunaimi-postgresql-data-production 