services:
  tsunaimi-website:
    build:
      context: ./apps/frontend/website
      dockerfile: Dockerfile
      target: development
    networks:
      - shared-network

networks:
  shared-network: {}