version: '3.8'

services:
  frontend:
    image: tsunaimi-website-frontend:${RELEASE_NAME}
    container_name: tsunaimi-frontend-staging
    restart: unless-stopped
    ports:
      - "3100:3000"
    env_file:
      - .env.staging
    environment:
      - NODE_ENV=production  # Changed from staging to production for optimization
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    depends_on:
      - postgresql
    networks:
      - tsunaimi-network-staging

  postgresql:
    image: tsunaimi-website-postgresql:${RELEASE_NAME}
    container_name: tsunaimi-postgresql-staging
    restart: unless-stopped
    ports:
      - "5532:5432"
    env_file:
      - .env.staging
    volumes:
      - tsunaimi-postgresql-data-staging:/var/lib/postgresql/data
    networks:
      - tsunaimi-network-staging

networks:
  tsunaimi-network-staging:
    name: tsunaimi-network-staging
    ipam:
      config:
        - subnet: 172.21.0.0/16

volumes:
  tsunaimi-postgresql-data-staging:
    name: tsunaimi-postgresql-data-staging