version: '3.8'

services:
  frontend:
    image: tsunaimi-website-frontend:${RELEASE_NAME}
    container_name: tsunaimi-frontend-production
    restart: unless-stopped
    ports:
      - "3200:3000"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    depends_on:
      - postgresql
    networks:
      - tsunaimi-network-production

  postgresql:
    image: tsunaimi-website-postgresql:${RELEASE_NAME}
    container_name: tsunaimi-postgresql-production
    restart: unless-stopped
    ports:
      - "5632:5432"
    env_file:
      - .env.production
    volumes:
      - tsunaimi-postgresql-data-production:/var/lib/postgresql/data
    networks:
      - tsunaimi-network-production

networks:
  tsunaimi-network-production:
    name: tsunaimi-network-production
    ipam:
      config:
        - subnet: 172.22.0.0/16

volumes:
  tsunaimi-postgresql-data-production:
    name: tsunaimi-postgresql-data-production 