services:
  postgresql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tsunaimi-postgresql-dev
    ports:
      - "${DB_PORT_EXTERNAL}:${DB_PORT_INTERNAL}"
    env_file:
      - .env.website-db.dev
    volumes:
      - tsunaimi-postgresql-data-dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - tsunaimi-network-dev

networks:
  tsunaimi-network-dev:
    name: tsunaimi-network-dev

volumes:
  tsunaimi-postgresql-data-dev:
    name: tsunaimi-postgresql-data-dev

# Set the project name based on environment
name: tsunaimi-website-${ENVIRONMENT:-dev} 